name: GunGame18
version: '1.0.0'
main: me.commandrod.gungame.Main
api-version: 1.8
authors: [ commandROD ]
commands:
  setspawn:
    description: Sets the spawn location.
    usage: /setspawn
  spawn:
    description: Teleports the player to spawn.
    usage: /spawn [player]
  setlevel:
    description: Sets a player's level.
    usage: /setlevel <level> [player]
  profile:
    description: Opens the profile GUI.
    usage: /profile